@startuml
title Activity Diagram – Membuat dan Mengubah Data Pada Fitur Check Sheet

'================================================
' STYLING
'================================================
skinparam backgroundColor #FAFAFA
skinparam DefaultFontName "Times New Roman"
skinparam defaultFontSize 14

skinparam Padding 3
skinparam PartitionHeaderFontStyle bold

skinparam ArrowColor #2E2E2E
skinparam ArrowThickness 2

skinparam ActivityBackgroundColor #FFFFFF
skinparam ActivityBorderColor #7A7A7A

skinparam StartColor #4CAF50
skinparam EndColor #E53935

skinparam DiamondBackgroundColor #FFF7CC
skinparam DiamondBorderColor #C5A600

!define ROLES Administrator\nOperator
!define SYSTEM #AntiqueWhite|System

'================================================
' PAGE 1 – ACCESS & MENU
'================================================
|ROLES|
start
:Login;
:Sorot Menu\nDocument;
:Pilih Menu\nCheck Sheet;
:Pilih Aksi;

if (Menambah Data?) then (Ya)
:Tekan Tombol\nNew Check Sheet;

|ROLES|
elseif (Mengubah Data)  then (Ya)
:Tekan Tombol\nEdit;
note
Tombol Dengan
Icon Pencil
endnote
|SYSTEM|
|ROLES|
else (No)
|ROLES|
end
endif

|SYSTEM|
:Redirect ke Halaman\nFormulir Pengisian\nCheck Sheet;
|ROLES|
:Mendefinisikan\nCheck Point;
:Mengisi Nilai Pada\nSetiap Check Point;
if (Apakah Sudah\nSelesai?) then (Ya)
:Simpan Sebagai\nDraft;
else (Tidak)
:Ajukan untuk\nPeninjauan;
endif
repeat
:Input & Submit Data;

|SYSTEM|
  :Validasi Data;
  backward:Menampilkan\nPesan Error;
repeat while (Valid?)



'================================================
' PAGE 3 – SAVE & RESULT
'================================================
|SYSTEM|
:Simpan Data;
:Menampilkan Pesan Sukses;
:Redirect ke Halaman Daftar Data;


stop
@enduml
