@startuml
skinparam backgroundColor #FAFAFA
skinparam DefaultFontName "Times New Roman"
skinparam defaultFontSize 14

skinparam Padding 5
skinparam PartitionHeaderFontStyle bold

skinparam ArrowColor #2E2E2E
skinparam ArrowThickness 2
skinparam ArrowFontSize 13
skinparam ArrowFontColor #1A1A1A

skinparam ActivityBackgroundColor #FFFFFF
skinparam ActivityBorderColor #7A7A7A
skinparam ActivityBorderThickness 1.2
skinparam ActivityFontColor #1A1A1A

skinparam StartColor #4CAF50
skinparam EndColor #E53935
skinparam StartFontColor white
skinparam EndFontColor white

skinparam DiamondBackgroundColor #FFF7CC
skinparam DiamondBorderColor #C5A600
skinparam DiamondFontColor #2A2A2A

skinparam NoteBackgroundColor #FFFDE7
skinparam NoteBorderColor #E0C66F

!define ROLES Administrator
!define SYSTEM #AntiqueWhite|System
|ROLES|
start
:Login;


 |ROLES|


|ROLES|
:Pilih Menu Check Sheet;

|SYSTEM|
if (Memiliki Akses?) then (Ya)
:Menampilkan Halaman
Daftar Check Sheet;

else (Tidak)
:Menampilkan Halaman
401 Unauthorized;
endif

stop
@enduml
