CREATE TABLE parameters
(
    id            SERIAL PRIMARY KEY,
    mqtt_topic_id BIGINT REFERENCES mqtt_topics (id) NOT NULL,
    name          VARCHAR(255)                       NOT NULL,
    code          VARCHAR(255)                       NOT NULL,
    unit          VARCHAR(255)                       NOT NULL,
    min_value     FLOAT,
    max_value     FLOAT,
    description   TEXT,
    position_x    FLOAT,
    position_y    FLOAT,
    position_z    FLOAT,
    rotation_x    FLOAT,
    rotation_y    FLOAT,
    rotation_z    FLOAT,
    is_display    BOOLEAN   DEFAULT TRUE             NOT NULL,
    is_automatic  BOOLEAN   DEFAULT TRUE             NOT NULL,
    created_by    VARCHAR(255),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by    VARCHAR(255),
    deleted_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    deleted_by    VARCHAR(255)
)