CREATE TYPE parameter_categories_enum AS ENUM ('Data', 'Status', 'Time');

CREATE TABLE parameters
(
    id                SERIAL PRIMARY KEY,
    machine_id        BIGINT REFERENCES machines (id),
    mqtt_topic_id     BIGINT REFERENCES mqtt_topics (id),
    name              VARCHAR(255)              NOT NULL,
    code              VARCHAR(255)              NOT NULL,
    unit              VARCHAR(255)              NOT NULL,
    min_value         FLOAT                     NOT NULL DEFAULT 0,
    max_value         FLOAT                     NOT NULL DEFAULT 0,
    description       TEXT,
    category          parameter_categories_enum NOT NULL DEFAULT 'Data',
    data_type         VARCHAR(255)              NOT NULL DEFAULT 'String',
    position_x        FLOAT                     NOT NULL DEFAULT 0,
    position_y        FLOAT                     NOT NULL DEFAULT 0,
    position_z        FLOAT                     NOT NULL DEFAULT 0,
    rotation_x        FLOAT                     NOT NULL DEFAULT 0,
    rotation_y        FLOAT                     NOT NULL DEFAULT 0,
    rotation_z        FLOAT                     NOT NULL DEFAULT 0,
    abnormal_duration INT                       NOT NULL DEFAULT 1,
    is_automatic      BOOLEAN                   NOT NULL DEFAULT TRUE,
    is_display        BOOLEAN                   NOT NULL DEFAULT FALSE,
    is_watch          BOOLEAN                   NOT NULL DEFAULT FALSE,
    is_featured       BOOLEAN                   NOT NULL DEFAULT FALSE,
    is_running_time   BOOLEAN                   NOT NULL DEFAULT FALSE,
    is_processed      BOOLEAN                   NOT NULL DEFAULT FALSE,
    created_by        VARCHAR(255),
    created_at        TIMESTAMP                          DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP                          DEFAULT CURRENT_TIMESTAMP,
    updated_by        VARCHAR(255),
    deleted_at        TIMESTAMP                          DEFAULT CURRENT_TIMESTAMP,
    deleted_by        VARCHAR(255)
)