@startuml
title Activity Diagram – Mengubah Data Pada Fitur Role & User

'================================================
' STYLING
'================================================
skinparam backgroundColor #FAFAFA
skinparam DefaultFontName "Times New Roman"
skinparam defaultFontSize 14

skinparam Padding 3
skinparam PartitionHeaderFontStyle bold

skinparam ArrowColor #2E2E2E
skinparam ArrowThickness 2

skinparam ActivityBackgroundColor #FFFFFF
skinparam ActivityBorderColor #7A7A7A

skinparam StartColor #4CAF50
skinparam EndColor #E53935

skinparam DiamondBackgroundColor #FFF7CC
skinparam DiamondBorderColor #C5A600

!define ROLES Administrator
!define SYSTEM #AntiqueWhite|System

'================================================
' PAGE 1 – ACCESS & MENU
'================================================
|ROLES|
start
:Login;
:Sorot Menu\nUser Management;
:Pilih Role & User;
:Pilih Aksi;

if (Mengubah Data\nUser?) then (Ya)
:Tekan Tombol \nEdit;
note
Tombol Dengan
Icon Pencil
endnote
|SYSTEM|
:Menampilkan Drawer\nFormulir Tambah Data;
|ROLES|
:Mengubah Field;
elseif (Mengubah Data\nRole)  then (Ya)
:Tekan Tombol\nEdit Role;
|SYSTEM|
:Menampilkan Dialog\nFormulir Tambah Data;
|ROLES|
:Mengubah Field;
:Memilih Permission\nyang Diberikan;
else (No)
|ROLES|
end
endif

|SYSTEM|
|ROLES|
repeat
:Submit Data;

|SYSTEM|
  :Validasi Data;
  backward:Menampilkan\nPesan Error;
repeat while (Valid?)


'================================================
' PAGE 3 – SAVE & RESULT
'================================================
|SYSTEM|
:Mengubah Data;
:Menampilkan Pesan Sukses;

if (Mengubah Data\nUser?) then (Ya)
:Menutup Drawer;
elseif (Mengubah Data\nRole)  then (Ya)
:Menutup Dialog;
else (No)
|SYSTEM|
end
endif
stop
@enduml
