@startuml
title Activity Diagram – Mengubah Data System Setting

'================================================
' STYLING
'================================================
skinparam backgroundColor #FAFAFA
skinparam DefaultFontName "Times New Roman"
skinparam defaultFontSize 14

skinparam Padding 3
skinparam PartitionHeaderFontStyle bold

skinparam ArrowColor #2E2E2E
skinparam ArrowThickness 2

skinparam ActivityBackgroundColor #FFFFFF
skinparam ActivityBorderColor #7A7A7A

skinparam StartColor #4CAF50
skinparam EndColor #E53935

skinparam DiamondBackgroundColor #FFF7CC
skinparam DiamondBorderColor #C5A600

!define ROLES Administrator
!define SYSTEM #AntiqueWhite|System

'================================================
' PAGE 1 – ACCESS & MENU
'================================================
|ROLES|
start
:Login;
:Pilih System Setting;
:Pilih Jenis Sytem Setting;
if (Dashboard Setting?) then (Ya)

|SYSTEM|
|ROLES|
elseif (Listener Settings)  then (Ya)
|SYSTEM|
|ROLES|
else (No)
|ROLES|
end
endif
|ROLES|
:Menekan Tombol Manage;
|SYSTEM|
|ROLES|
repeat
:Mengisi Formulir;
:Submit Data;

|SYSTEM|
  :Validasi Data;
  backward:Menampilkan\nPesan Error;
repeat while (Valid?)


'================================================
' PAGE 3 – SAVE & RESULT
'================================================
|SYSTEM|
:Simpan Data;
:Menampilkan Pesan Sukses;
:Redirect ke Halaman\nJenis Setting;
stop
@enduml
