@startuml
title **Activity – Membuat Data MQTT Broker**

skinparam backgroundColor #FAFAFA
skinparam DefaultFontName "Times New Roman"
skinparam defaultFontSize 14

skinparam Padding 5
skinparam PartitionHeaderFontStyle bold

skinparam ArrowColor #2E2E2E
skinparam ArrowThickness 2
skinparam ArrowFontSize 13
skinparam ArrowFontColor #1A1A1A

skinparam ActivityBackgroundColor #FFFFFF
skinparam ActivityBorderColor #7A7A7A
skinparam ActivityBorderThickness 1.2
skinparam ActivityFontColor #1A1A1A

skinparam StartColor #4CAF50
skinparam EndColor #E53935
skinparam StartFontColor white
skinparam EndFontColor white

skinparam DiamondBackgroundColor #FFF7CC
skinparam DiamondBorderColor #C5A600
skinparam DiamondFontColor #2A2A2A

skinparam NoteBackgroundColor #FFFDE7
skinparam NoteBorderColor #E0C66F

!define ROLES Administrator
!define SYSTEM #AntiqueWhite|System

|ROLES|
start
:Akses Sistem;

|SYSTEM|
if (Sudah Login?) then (Ya)
else (Tidak)
  :Menampilkan Halaman Login;

  |ROLES|
  repeat
    :Input Kredensial;
    :Klik Login;

    |SYSTEM|
    :Validasi Kredensial;
    backward:Menampilkan\nPesan Error;
  repeat while (Valid?) is (Tidak)

  |SYSTEM|
endif
  :Menampilkan Dashboard;

|ROLES|
:Pilih Menu MQTT Broker;
:Tekan Tombol New MQTT Broker;

|SYSTEM|
:Menampilkan Formulir;

|ROLES|
repeat
  :Input Informasi MQTT Broker;
  :Submit;

  |SYSTEM|
  :Melakukan Validasi;
  backward:Menampilkan\nPesan Error;
repeat while (Valid?) is (Tidak)

|SYSTEM|
:Simpan MQTT Broker Baru;
:Menampilkan Pesan Sukses;
:Redirect ke Halaman Daftar MQTT Broker;
:Menampilkan Halaman Daftar MQTT Broker;

stop
@enduml
